#!/bin/bash

set -e

ENV_FILE="garage.env"
KEY_NAME="swompi"

if [ -f "$ENV_FILE" ] && grep -q "S3_ACCESS_KEY" "$ENV_FILE"; then
    echo "Garage keys already exist in ${ENV_FILE}. Skipping creation."
    exit 0
fi

echo "Garage keys not found. Creating new keys..."


GARAGE_OUTPUT=$(/garage key create "$KEY_NAME")

# Используем grep и awk для "вырезания" нужных значений. Это надежно.
# awk '{print $NF}' - берет последнее поле в строке
ACCESS_KEY=$(echo "$GARAGE_OUTPUT" | grep "Key ID:" | awk '{print $NF}')
SECRET_KEY=$(echo "$GARAGE_OUTPUT" | grep "Secret key:" | awk '{print $NF}')

if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ]; then
    echo "!!! CRITICAL: Failed to parse keys from garage output."
    echo "Output was:"
    echo "$GARAGE_OUTPUT"
    exit 1
fi

echo "Keys created successfully. Granting permissions..."

garage key allow "$KEY_NAME" --create-bucket

echo "Permissions granted. Writing to ${ENV_FILE}..."

cat <<EOF > "$ENV_FILE"
# Auto-generated by init-garage.sh on $(date)
S3_ENDPOINT_URL="http://garage:3900"
S3_ACCESS_KEY="${ACCESS_KEY}"
S3_SECRET_KEY="${SECRET_KEY}"
EOF

chmod 644 "$ENV_FILE"

echo "✅ Garage initialization complete. .env file is ready."