#!/bin/bash
set -e 

CONFIG_FILE="/etc/garage.toml"
ENV_FILE="/data/.garage.env"
KEY_NAME="swompi"

if [ -f "$ENV_FILE" ] && grep -q "S3_ACCESS_KEY" "$ENV_FILE"; then
    echo "S3 keys already exist in ${ENV_FILE}. Skipping creation."
else
    echo "S3 keys not found. Creating new keys..."

    /garage server &
    GARAGE_PID=$!

    for i in {1..10}; do
        sleep 2
    done

    NODE_ID=$(/garage status | grep -E '^[0-9a-f]{16}' | awk '{print $1}')
    echo "Found Node ID: ${NODE_ID}"
    /garage layout assign -z dc1 -c 1G "$NODE_ID"
    /garage layout apply --version 1

    GARAGE_OUTPUT=$(/garage key create "$KEY_NAME")
    ACCESS_KEY=$(echo "$GARAGE_OUTPUT" | grep "Key ID:" | awk '{print $NF}')
    SECRET_KEY=$(echo "$GARAGE_OUTPUT" | grep "Secret key:" | awk '{print $NF}')

    if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ]; then
        echo "CRITICAL: Failed to parse keys from garage output."
        exit 1
    fi
    
    /garage key allow "$KEY_NAME" --create-bucket
    echo "Permissions granted. Writing to ${ENV_FILE}..."

    cat <<EOF > "$ENV_FILE"
# Auto-generated by init-garage.sh on $(date)
S3_ENDPOINT_URL="http://garage:3900"
S3_ACCESS_KEY="${ACCESS_KEY}"
S3_SECRET_KEY="${SECRET_KEY}"
S3_DEFAULT_REGION="garage"
EOF
    echo "S3 keys file is ready."
    kill $GARAGE_PID
    wait $GARAGE_PID || true
fi


echo "Starting Garage Server"
exec /garage server